# Generated by Django 6.0.1 on 2026-02-04 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('product', models.TextField()),
                ('subject', models.CharField(max_length=255)),
            ],
        ),
    ]
